<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aleph Initial Alpha, Virtual CSSERG">
<meta name="dcterms.date" content="2026-09-25">

<title>1&nbsp; Predict the Self – Predict the Self</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0a7cdd05051b86812d7947ffad15333a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">


<link rel="stylesheet" href="report.css">
</head>

<body class="nav-sidebar floating quarto-light">
<a class="report-skip" href="#quarto-document-content">Skip to content</a>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" aria-label="Report navigation">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./report.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Predict the Self</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto" aria-label="Report chapters">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Predict the Self</a>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container">
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Forecasting expressed identity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./report.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Predict the Self</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" aria-label="On this page">
    <h2 id="toc-title">Table of contents</h2>

  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">2</span> Abstract</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings"><span class="header-section-number">3</span> Findings at a glance</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">4</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question"><span class="header-section-number">4.1</span> Research question</a></li>
  <li><a href="#benchmark" id="toc-benchmark" class="nav-link" data-scroll-target="#benchmark"><span class="header-section-number">4.2</span> Benchmark and provenance</a></li>
  </ul></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method"><span class="header-section-number">5</span> Method</a>
  <ul class="collapse">
  <li><a href="#stable-signifier-projection" id="toc-stable-signifier-projection" class="nav-link" data-scroll-target="#stable-signifier-projection"><span class="header-section-number">5.1</span> Stable-signifier projection</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection"><span class="header-section-number">5.2</span> Model selection</a></li>
  <li><a href="#locked-training-cross-validation-of-the-stable-projection" id="toc-locked-training-cross-validation-of-the-stable-projection" class="nav-link" data-scroll-target="#locked-training-cross-validation-of-the-stable-projection"><span class="header-section-number">5.3</span> Locked training cross-validation of the stable projection</a></li>
  <li><a href="#post-hoc-development-diagnostics" id="toc-post-hoc-development-diagnostics" class="nav-link" data-scroll-target="#post-hoc-development-diagnostics"><span class="header-section-number">5.4</span> Post hoc development diagnostics</a></li>
  <li><a href="#locked-matched-trajectory-retrieval" id="toc-locked-matched-trajectory-retrieval" class="nav-link" data-scroll-target="#locked-matched-trajectory-retrieval"><span class="header-section-number">5.5</span> Locked matched-trajectory retrieval</a></li>
  <li><a href="#post-hoc-volume-matched-novelty-control" id="toc-post-hoc-volume-matched-novelty-control" class="nav-link" data-scroll-target="#post-hoc-volume-matched-novelty-control"><span class="header-section-number">5.6</span> Post hoc volume-matched novelty control</a></li>
  <li><a href="#locked-training-only-source-conditioned-ranking" id="toc-locked-training-only-source-conditioned-ranking" class="nav-link" data-scroll-target="#locked-training-only-source-conditioned-ranking"><span class="header-section-number">5.7</span> Locked training-only source-conditioned ranking</a></li>
  <li><a href="#locked-regularized-neighborhood-ranking" id="toc-locked-regularized-neighborhood-ranking" class="nav-link" data-scroll-target="#locked-regularized-neighborhood-ranking"><span class="header-section-number">5.8</span> Locked regularized-neighborhood ranking</a></li>
  <li><a href="#locked-prospective-change-volume-forecasting" id="toc-locked-prospective-change-volume-forecasting" class="nav-link" data-scroll-target="#locked-prospective-change-volume-forecasting"><span class="header-section-number">5.9</span> Locked prospective change-volume forecasting</a></li>
  <li><a href="#locked-probabilistic-change-volume-forecasting" id="toc-locked-probabilistic-change-volume-forecasting" class="nav-link" data-scroll-target="#locked-probabilistic-change-volume-forecasting"><span class="header-section-number">5.10</span> Locked probabilistic change-volume forecasting</a></li>
  <li><a href="#locked-source-feature-ablation" id="toc-locked-source-feature-ablation" class="nav-link" data-scroll-target="#locked-source-feature-ablation"><span class="header-section-number">5.11</span> Locked source-feature ablation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">6</span> Results</a>
  <ul class="collapse">
  <li><a href="#aggregate-scorecard" id="toc-aggregate-scorecard" class="nav-link" data-scroll-target="#aggregate-scorecard"><span class="header-section-number">6.1</span> Aggregate scorecard</a></li>
  <li><a href="#paired-pattern" id="toc-paired-pattern" class="nav-link" data-scroll-target="#paired-pattern"><span class="header-section-number">6.2</span> Paired development-case pattern</a></li>
  <li><a href="#stable-projection-cv" id="toc-stable-projection-cv" class="nav-link" data-scroll-target="#stable-projection-cv"><span class="header-section-number">6.3</span> Training cross-validation repeats the mixed pattern</a></li>
  <li><a href="#extractive-limits" id="toc-extractive-limits" class="nav-link" data-scroll-target="#extractive-limits"><span class="header-section-number">6.4</span> Lexical novelty and extractive ceilings</a></li>
  <li><a href="#trajectory-retrieval" id="toc-trajectory-retrieval" class="nav-link" data-scroll-target="#trajectory-retrieval"><span class="header-section-number">6.5</span> Retrieval predicts novelty volume, not novel content</a></li>
  <li><a href="#novelty-prior" id="toc-novelty-prior" class="nav-link" data-scroll-target="#novelty-prior"><span class="header-section-number">6.6</span> Person matching does not beat common additions</a></li>
  <li><a href="#source-conditioned-additions" id="toc-source-conditioned-additions" class="nav-link" data-scroll-target="#source-conditioned-additions"><span class="header-section-number">6.7</span> Source-token conditioning also loses to common additions</a></li>
  <li><a href="#neighborhood-additions" id="toc-neighborhood-additions" class="nav-link" data-scroll-target="#neighborhood-additions"><span class="header-section-number">6.8</span> Regularized neighborhoods still lose to common additions</a></li>
  <li><a href="#change-volume" id="toc-change-volume" class="nav-link" data-scroll-target="#change-volume"><span class="header-section-number">6.9</span> Neighborhoods predict some revision volume</a></li>
  <li><a href="#change-distributions" id="toc-change-distributions" class="nav-link" data-scroll-target="#change-distributions"><span class="header-section-number">6.10</span> Neighborhood distributions improve only word-count forecasts</a></li>
  <li><a href="#feature-ablation" id="toc-feature-ablation" class="nav-link" data-scroll-target="#feature-ablation"><span class="header-section-number">6.11</span> Earlier self-description carries most word-count signal</a></li>
  <li><a href="#submission" id="toc-submission" class="nav-link" data-scroll-target="#submission"><span class="header-section-number">6.12</span> Frozen test submission</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">7</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility"><span class="header-section-number">7.1</span> Reproducibility</a></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources"><span class="header-section-number">7.2</span> Sources</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">7.3</span> Limitations and next step</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Predict the Self</span></h1>
<p class="subtitle lead">Evidence, method, and benchmark diagnostics</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aleph Initial Alpha, Virtual CSSERG </p>
          </div>
  </div>

    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 25, 2026</p>
    </div>
  </div>


  </div>



</header>


<p><a class="report-brand" href="../../../" aria-label="Virtual CSSERG home"><img src="../../../images/csserg-transparent-logo.png" alt="CSSERG logo"><span>Virtual CSSERG</span></a></p>
<p><a href="../index.html">Executive Summary</a> · <a href="../short-report.pdf">Short two-column report</a> · <a href="index.html">report landing page</a></p>
<section id="abstract" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Abstract</h1>
<p>An 81-case test submission is frozen and passes the official format validator. Because test answers are private, this report does not claim a test score. On 50 public development cases, a deterministic stable-signifier projection has mixed agreement results relative to repeating the 2024 response verbatim. A new post hoc analysis finds that the small agreement differences are sensitive to which development cases are included, while improvements in word-count and source-similarity error are more stable. More fundamentally, 73.2% of distinct tokens in an average observed follow-up did not appear in that person’s earlier response, exposing a severe limit for any strictly extractive forecast. A locked exploratory baseline retrieves the complete follow-up of the most similar training participant. It approximates how much new vocabulary will appear but not which vocabulary: predicted unique-token novelty is 80.2% versus 73.2% observed, while mean novel-token precision is 7.0%, recall is 8.5%, and agreement is lower than both continuity baselines. A post hoc volume-matched control sharpens the result: simply choosing the most frequent training-set additions reaches 17.7% precision and 14.3% F1, versus 7.0% and 6.7% for person-matched retrieval. A locked training-only leave-one-out test then asks whether earlier source tokens can improve that marginal ranking. The fixed source-conditioned rule recovers 14.5% of held-out additions versus 16.1% for the marginal prior. A second locked test pools and regularizes 30 similar text-and-demographic trajectories; it recovers 14.9% versus the same 16.1% marginal result, a paired difference of −1.20 percentage points (95% case-bootstrap interval: −1.84 to −0.57). Neither individualized ranking demonstrates incremental content advantage. A third locked leave-one-out test removes the oracle budget and forecasts how much each held-out response will change. The same regularized neighborhood lowers MAE relative to source- calibrated fold medians for Add count (<code>20.126667</code> versus <code>21.340000</code>), Delete count (<code>5.336275</code> versus <code>5.614935</code>), and word count (<code>52.940000</code> versus <code>56.080000</code>); all three paired intervals exclude zero. It ties on line count, while the source-similarity interval spans zero. A fourth lock evaluates the complete predictive distributions rather than only their medians. The neighborhood improves word-count CRPS (<code>38.156852</code> versus <code>40.672695</code>; paired reduction <code>+2.515843</code>, interval <code>+1.008212</code> to <code>+4.059792</code>) and its central 80% interval score, while CRPS intervals for the other four outcomes span zero. A fifth locked analysis separates the combined source representation. Text-only matching improves word-count CRPS over the marginal by <code>+2.298139</code> (interval <code>+0.816444</code> to <code>+3.865823</code>); demographics-only matching does not, although adding demographics to text yields a smaller incremental gain of <code>+0.217704</code> (<code>+0.024229</code> to <code>+0.420871</code>). A separately locked leave-one-out cross-validation of the frozen stable projection repeats its central mixed pattern: edit similarity improves by <code>0.004147</code>, token-overlap F1 worsens by <code>0.003493</code>, word-count and source-similarity error fall, and line-count error rises. The other non-exact agreement intervals span zero.</p>
</section>
<section id="findings" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Findings at a glance</h1>
<ul>
<li>The benchmark is now pinned to commit <a href="https://github.com/jasonjeffreyjones/predict-future-selves/tree/9b6a766712583fec8d3182957260b1123fbfa146"><code>9b6a766</code></a>, and every governing input has a recorded SHA-256 checksum.</li>
<li>The deterministic method learns which source tokens recur in later self-description and extracts high-persistence response units to a training-predicted length.</li>
<li>Relative to repeat-2024 on development data, it has higher normalized edit similarity, token Jaccard similarity, and ROUGE-L F1, and lower word-count and source-similarity error.</li>
<li>It also has lower token-overlap F1 and character n-gram F1 and higher line-count error. There is no composite score or defensible “overall winner.”</li>
<li>Paired case-bootstrap intervals span zero for all five nonzero agreement differences; only error in length and amount of change has a clearer pattern.</li>
<li>Leave-one-out prediction of all 150 training trajectories repeats that mixed pattern without using each case’s own follow-up in its fitted model. It does not convert method-development data into untouched confirmation.</li>
<li>It still forecasts too much continuity: mean prediction-to-source ROUGE-L is 0.903898, compared with 0.225683 for observed follow-ups.</li>
<li>On average, 73.2% of follow-up unique token types are new relative to the earlier response and therefore unavailable to a strictly extractive method.</li>
<li>Matched-trajectory retrieval approximates the volume of lexical novelty and reduces source-similarity error, but its retrieved new signifiers rarely match the focal person’s observed new signifiers.</li>
<li>At identical case-level novelty volume, a marginal prior based only on common training additions recovers more observed new token types than person-matched retrieval on 40 of 50 development cases.</li>
<li>In a separate leave-one-out analysis of all 150 training trajectories, the locked source-conditioned Add ranking performs worse than its marginal comparator on 68 cases, ties 63, and wins 19 at the same oracle token budget.</li>
<li>A strongly regularized 30-neighbor Add ranking also falls short: it loses 65 cases, ties 60, and wins 25, despite changing 26.0% of marginal-prior guesses on an average case.</li>
<li>Without an oracle future-token budget, that fixed neighborhood does improve leave-one-out forecasts of Add count, Delete count, and follow-up word count over source-calibrated fold medians. It does not improve line count or show a stable source-similarity advantage.</li>
<li>Full predictive distributions sharpen that result: neighborhood word-count CRPS and central 80% interval score improve, but Add count, Delete count, line count, and source-similarity CRPS differences remain compatible with zero.</li>
<li>A locked ablation locates most of that word-count signal in earlier self-description text. Demographics alone do not improve over the marginal, although they add a small incremental gain when combined with text.</li>
</ul>
</section>
<section id="introduction" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Introduction</h1>
<section id="research-question" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="research-question"><span class="header-section-number">4.1</span> Research question</h2>
<p>The larger project asks how predictable human lives are. Its first tractable task is Dr.&nbsp;Jason Jeffrey Jones’ <a href="https://github.com/jasonjeffreyjones/predict-future-selves">Predict Future Selves challenge</a>: predict a later self-authored self-description from an earlier self-authored self-description.</p>
<p>This is an ipseological prediction task. A Twenty Statements Test response is <em>personally expressed identity</em>: text an individual provides to describe themself. Words and phrases may act as identity signifiers. The target is a later expression of identity—not a latent “true self” and not a complete life outcome.</p>
</section>
<section id="benchmark" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="benchmark"><span class="header-section-number">4.2</span> Benchmark and provenance</h2>
<p>The benchmark contains 281 Prolific participants with approved, complete Twenty Statements Test responses in the 2024 study and its longitudinal follow-up. Follow-up responses were recorded 424 to 750 days later (median 433). The deterministic split contains 150 training, 50 development, and 81 test cases. Training and development responses are paired; test follow-ups and follow-up demographics are private.</p>
<p>The project retrieved the public repository on 2026-08-30 and detached the checkout at commit <code>9b6a766712583fec8d3182957260b1123fbfa146</code> before prediction. The four input hashes and the hashes of the governing documentation, evaluator, and validator are recorded in <a href="BENCHMARK_PROVENANCE.md"><code>BENCHMARK_PROVENANCE.md</code></a>.</p>
<p>The benchmark’s own warnings govern interpretation: the sample is small and selected; platform recruitment and longitudinal attrition limit generalization; and agreement with one observed follow-up does not establish that a prediction was the only plausible future.</p>
</section>
</section>
<section id="method" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Method</h1>
<section id="stable-signifier-projection" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="stable-signifier-projection"><span class="header-section-number">5.1</span> Stable-signifier projection</h2>
<p>The method is deterministic and extractive. It uses the 150 public training pairs and no external data or model.</p>
<ol type="1">
<li>For every source token, estimate the proportion of training documents in which that token also appears at follow-up. Smooth toward the corpus-wide retention rate with ten equivalent prior observations.</li>
<li>Divide each source response using its strongest repeated boundary: lines, sentences, comma phrases, or the complete response.</li>
<li>Score each response unit by the mean estimated retention probability of its unique content tokens.</li>
<li>Fit a training-only ordinary least squares regression of follow-up word count on source word count.</li>
<li>Retain high-scoring units while doing so moves the response closer to the predicted length, then restore their original order.</li>
</ol>
<p>Demographic metadata is not used. The method has no random choices and no case-level manual editing. It is deliberately interpretable: every predicted word comes from that person’s earlier self-description.</p>
</section>
<section id="model-selection" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="model-selection"><span class="header-section-number">5.2</span> Model selection</h2>
<p>Public development data were used for model selection, as the challenge allows. Fixed extraction fractions and the training-only length regression were compared; the regression-length rule was frozen before the test artifact was generated. The development scorecard is therefore a model-selection result, not an untouched confirmatory estimate.</p>
</section>
<section id="locked-training-cross-validation-of-the-stable-projection" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="locked-training-cross-validation-of-the-stable-projection"><span class="header-section-number">5.3</span> Locked training cross-validation of the stable projection</h2>
<p>Before generating any fold prediction, the Project fixed a leave-one-out plan at SHA-256 <code>2929b1fb8111c42170d23e725c08f6167135d9a703a1b61e87ed59af5f97c5d8</code> and hash-guarded the unchanged generator. Each of the 150 training cases is held out in turn; the original retention estimator and length regression are refit on the other 149, with the same ten-observation smoothing prior, and the held-out response is predicted from its 2024 text alone. Repeat-2024 is the paired comparator.</p>
<p>The analysis reports the full official scorecard and 20,000 paired case- bootstrap resamples with seed <code>20260922</code>. It is a cross-validation diagnostic, not a preregistration or fresh confirmation: the training corpus and public development results informed earlier method development. Withholding each case’s own follow-up prevents direct fold leakage, but it cannot erase that history or establish population generalization.</p>
</section>
<section id="post-hoc-development-diagnostics" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="post-hoc-development-diagnostics"><span class="header-section-number">5.4</span> Post hoc development diagnostics</h2>
<p>After freezing the model and predictions, later work added two descriptive diagnostics. First, every scorecard comparison was decomposed into 50 paired case differences. A deterministic percentile bootstrap resampled cases in pairs 20,000 times (seed <code>20260917</code>) to show how the mean effect changes with development-case composition. These intervals do not warrant population generalization, and the analysis was not preregistered.</p>
<p>Second, tokenized 2024 and follow-up responses were compared case by case. Unique-token novelty is the share of follow-up token types absent from the earlier response. Occurrence unavailability additionally respects how many times each token appears in the source: a strictly extractive method cannot copy a token more often than it occurs there. Three deliberately unattainable oracles use each observed follow-up to select the best source token set, bag of words, or source-order subsequence. They describe extractive ceilings, not prospective prediction performance.</p>
</section>
<section id="locked-matched-trajectory-retrieval" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="locked-matched-trajectory-retrieval"><span class="header-section-number">5.5</span> Locked matched-trajectory retrieval</h2>
<p>A second method was locked before its predictions were generated. This is a prospective analysis lock, not a preregistration: the development labels and aggregate stable-projection results were examined in earlier work, so the comparison remains exploratory. The complete plan was fixed at SHA-256 <code>86b2ddfe775773e1964beeefbac5479d88f6c46cd3385bf3a992fc7ae64e9c83</code>.</p>
<p>Four one-nearest-neighbor variants were first compared by leave-one-out prediction among the 150 training pairs. TF-IDF cosine over text plus 2024 demographics had the highest training token-overlap F1 (<code>0.1925</code>) and was selected by that declared lexical criterion. For each development query, the locked method:</p>
<ol type="1">
<li>represents case-folded response tokens and field-qualified, nonblank 2024 demographic values with smoothed TF-IDF weights;</li>
<li>selects the training source with greatest cosine similarity, breaking ties by training-file order; and</li>
<li>uses that neighbor’s observed follow-up verbatim as the prediction.</li>
</ol>
<p>The baseline is non-extractive with respect to the focal person’s earlier response, but it retrieves rather than synthesizes. It deliberately tests whether a prior person’s trajectory supplies the right kind and amount of new content. It generated development predictions only and did not create or alter a test submission. The copied training text is public benchmark data licensed CC BY-NC-SA 4.0 and is presented only as an auditable baseline, not as a factual description of the focal participant.</p>
<p>The same complete scorecard is reported below. Directional metrics were also compared within person using 20,000 paired case-bootstrap resamples (seed <code>20260918</code>). Additional diagnostics compare predicted and observed novelty and measure precision, recall, and F1 for predicted novel token types. As above, the intervals describe development-case composition rather than a population.</p>
</section>
<section id="post-hoc-volume-matched-novelty-control" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="post-hoc-volume-matched-novelty-control"><span class="header-section-number">5.6</span> Post hoc volume-matched novelty control</h2>
<p>The retrieval method introduces many token types, creating more opportunities for chance overlap with the observed follow-up. A new diagnostic therefore holds this opportunity constant case by case. It counts, among the 150 training pairs, how many people add each token type between waves. For each development source, it excludes tokens already present and chooses the most frequently added remaining types, breaking frequency ties alphabetically. The number chosen is exactly the number of novel types emitted by retrieval for that case.</p>
<p>This marginal-addition prior uses no development response to construct its ranking, and it has the same novel-token budget as retrieval on every case. However, it borrows that budget from retrieval and produces only a token set, not a coherent response. It is therefore a diagnostic control rather than a standalone challenge forecast. The comparison was devised after development labels had already been inspected and is explicitly post hoc. Lexical tokens also include function words and other language that need not be semantic identity signifiers.</p>
</section>
<section id="locked-training-only-source-conditioned-ranking" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="locked-training-only-source-conditioned-ranking"><span class="header-section-number">5.7</span> Locked training-only source-conditioned ranking</h2>
<p>A final diagnostic tests individualization without using the development cases again. Its plan was fixed before implementation and scoring at SHA-256 <code>e65f04fd9e55843db8ff1a1bb0544acb00ec869eb58f9b312a63d531fc5f4ec9</code>. This is an analysis lock, not a preregistration: the training pairs had already informed earlier methods.</p>
<p>Each of the 150 training cases is held out in turn. On the other 149, the analysis counts marginal Add events and every association between a token in the source and a different token added at follow-up. For a candidate addition, the source-conditioned score is its largest conditional Add rate across the held-out person’s source tokens, smoothed toward the candidate’s marginal Add rate with ten prior cases. That prior strength was fixed to match the stable projection’s existing smoothing choice. Ties favor marginal frequency and then alphabetical token order.</p>
<p>Both rankings receive exactly as many guesses as the held-out follow-up actually adds. This oracle budget isolates token ordering but disqualifies both rankings as standalone forecasts. Because predicted and observed token sets have equal size, case-level precision, recall, and F1 are identical; the report calls their shared value the recovered fraction. A 20,000-resample paired case bootstrap uses seed <code>20260920</code>.</p>
</section>
<section id="locked-regularized-neighborhood-ranking" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="locked-regularized-neighborhood-ranking"><span class="header-section-number">5.8</span> Locked regularized-neighborhood ranking</h2>
<p>A second training-only plan was fixed before implementation or scoring at SHA-256 <code>c7a494327dd1dd7fc83911540a6a9095fcc8d684172a7388bd610206ac4ca13d</code>. It tests whether pooling multiple similar trajectories avoids the sparse-cue problem of the source-token rule. The source representation is reused from the earlier retrieval analysis: fold-fit TF-IDF over source text and field-qualified 2024 demographics.</p>
<p>For each held-out case, the other 149 cases form the training fold. The method selects the 30 most cosine-similar sources, weights their Add events by similarity, and rescales the weights to 30 effective cases. Each candidate’s weighted neighborhood count is then combined with 30 equivalent cases at its fold-wide marginal Add rate. This one-to-one shrinkage and the neighborhood size were fixed rather than tuned. The comparator is the same leave-one-out marginal ranking; both receive the held-out case’s observed addition count as an oracle budget. A 20,000-resample paired case bootstrap uses seed <code>20260921</code>. The plan is an analysis lock, not a preregistration, because both the training data and source representation informed earlier work.</p>
</section>
<section id="locked-prospective-change-volume-forecasting" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="locked-prospective-change-volume-forecasting"><span class="header-section-number">5.9</span> Locked prospective change-volume forecasting</h2>
<p>A third training-only plan was fixed before retrieving the benchmark in this iteration, implementation, or scoring at SHA-256 <code>53c974fcd37f443ea846e88328a125169265fb41ac1cc7877529bdbf9a09638f</code>. It reuses the same 30-neighbor text-and-demographic representation and equal 30-case neighborhood/prior weights, but removes the oracle future-token budget. The question is now whether similarity helps forecast response form and the <em>number</em> of Add and Delete events.</p>
<p>For each held-out case, the other 149 provide five modeled quantities: Add count; Delete count as a fraction of the source’s distinct token count; follow-up-minus-source word and nonempty-line counts; and follow-up-to-source ROUGE-L. A source-calibrated marginal forecast uses the fold median. The neighborhood forecast uses a weighted median combining 30 similarity-weighted neighbors with a 30-case prior spread across the whole fold. Fractions and changes are transformed back using only the held-out 2024 response. The analysis therefore uses no follow-up-derived budget or other held-out future information for prediction.</p>
<p>The primary effect is marginal absolute error minus neighborhood absolute error, so positive values favor person conditioning. Twenty thousand paired case-bootstrap resamples use seed <code>20260923</code>, restarted for each outcome. This lock cannot undo earlier use of the training corpus or earlier selection of the representation and hyperparameters.</p>
</section>
<section id="locked-probabilistic-change-volume-forecasting" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="locked-probabilistic-change-volume-forecasting"><span class="header-section-number">5.10</span> Locked probabilistic change-volume forecasting</h2>
<p>A fourth training-only plan extends that fixed volume model from point forecasts to complete predictive distributions. It was locked before reopening the benchmark in this iteration, implementation, or scoring at SHA-256 <code>00d5e2805082986b00f2716808ee12d4cff70ec900a5e47636e893217368f020</code>. For each held-out case and outcome, the marginal distribution gives equal weight to all 149 fold observations. The neighborhood distribution combines a 30-case fold-wide prior with the same 30 cosine-weighted neighbors used above. Every support point is transformed to the held-out source scale before scoring.</p>
<p>The primary score is the continuous ranked probability score (CRPS), a proper score that rewards predictive distributions concentrated near the observation (Gneiting &amp; Raftery, 2007); lower values are better. Secondary diagnostics use central 80% intervals and report inclusive coverage, width, and interval score, which penalizes both width and misses. Positive paired effects are marginal score minus neighborhood score. Twenty thousand paired case-bootstrap resamples use seed <code>20260924</code>, restarted for each outcome and score. Representation, neighborhood size, and shrinkage remain unchanged and untuned.</p>
</section>
<section id="locked-source-feature-ablation" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="locked-source-feature-ablation"><span class="header-section-number">5.11</span> Locked source-feature ablation</h2>
<p>A fifth training-only plan was locked before reopening the benchmark in this iteration, implementation, or scoring at SHA-256 <code>ed9fa67b2cc1265f3710471f96d7ffbfd16986b8295ef5072da26c263d8b7da4</code>. It asks whether the previously observed word-count distribution gain comes from the earlier self-description, the ten 2024 demographic fields, or their combination. It splits the unchanged TF-IDF representation into text-only, demographics-only, and combined feature sets without changing any field, neighbor, weighting, shrinkage, transformation, or scoring rule.</p>
<p>Follow-up word-count CRPS is primary because it was the only outcome with a supported combined-neighborhood CRPS gain in the preceding lock. The four other outcomes are prespecified secondary diagnostics. Four paired contrasts compare each ablation with the marginal distribution and the combined model. Twenty thousand case-bootstrap resamples use seed <code>20260925</code>, restarted for each outcome and contrast. Before any ablation result is accepted, the script must numerically reproduce every marginal and combined case-level CRPS value in the preceding locked audit.</p>
</section>
</section>
<section id="results" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Results</h1>
<section id="aggregate-scorecard" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="aggregate-scorecard"><span class="header-section-number">6.1</span> Aggregate scorecard</h2>
<p>The authoritative shared evaluator reports fifteen measures in three groups. The table reports every measure; arrows indicate the evaluator’s direction where one exists.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Group</th>
<th scope="col">Metric</th>
<th style="text-align: right;" scope="col">Stable projection</th>
<th style="text-align: right;" scope="col">Trajectory retrieval</th>
<th style="text-align: right;" scope="col">Repeat 2024</th>
<th scope="col">Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agreement</td>
<td>Normalized exact-match rate</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td>Higher</td>
</tr>
<tr class="even">
<td>Agreement</td>
<td>Normalized edit similarity</td>
<td style="text-align: right;">0.298061</td>
<td style="text-align: right;">0.253360</td>
<td style="text-align: right;">0.291966</td>
<td>Higher</td>
</tr>
<tr class="odd">
<td>Agreement</td>
<td>Token Jaccard similarity</td>
<td style="text-align: right;">0.142768</td>
<td style="text-align: right;">0.080427</td>
<td style="text-align: right;">0.141930</td>
<td>Higher</td>
</tr>
<tr class="even">
<td>Agreement</td>
<td>Token-overlap F1</td>
<td style="text-align: right;">0.307444</td>
<td style="text-align: right;">0.194693</td>
<td style="text-align: right;">0.312202</td>
<td>Higher</td>
</tr>
<tr class="odd">
<td>Agreement</td>
<td>ROUGE-L F1</td>
<td style="text-align: right;">0.227552</td>
<td style="text-align: right;">0.150924</td>
<td style="text-align: right;">0.225683</td>
<td>Higher</td>
</tr>
<tr class="even">
<td>Agreement</td>
<td>Character n-gram F1</td>
<td style="text-align: right;">0.292293</td>
<td style="text-align: right;">0.212660</td>
<td style="text-align: right;">0.296534</td>
<td>Higher</td>
</tr>
<tr class="odd">
<td>Form</td>
<td>Word-count MAE</td>
<td style="text-align: right;">41.640000</td>
<td style="text-align: right;">59.640000</td>
<td style="text-align: right;">56.680000</td>
<td>Lower</td>
</tr>
<tr class="even">
<td>Form</td>
<td>Line-count MAE</td>
<td style="text-align: right;">9.760000</td>
<td style="text-align: right;">8.340000</td>
<td style="text-align: right;">6.800000</td>
<td>Lower</td>
</tr>
<tr class="odd">
<td>Form</td>
<td>Mean predicted word count</td>
<td style="text-align: right;">77.320000</td>
<td style="text-align: right;">99.280000</td>
<td style="text-align: right;">108.040000</td>
<td>Descriptive</td>
</tr>
<tr class="even">
<td>Form</td>
<td>Mean reference word count</td>
<td style="text-align: right;">94.760000</td>
<td style="text-align: right;">94.760000</td>
<td style="text-align: right;">94.760000</td>
<td>Descriptive</td>
</tr>
<tr class="odd">
<td>Change</td>
<td>Prediction repeat-2024 rate</td>
<td style="text-align: right;">0.280000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">1.000000</td>
<td>Descriptive</td>
</tr>
<tr class="even">
<td>Change</td>
<td>Observed repeat-2024 rate</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td>Descriptive</td>
</tr>
<tr class="odd">
<td>Change</td>
<td>Source-similarity MAE</td>
<td style="text-align: right;">0.678215</td>
<td style="text-align: right;">0.136074</td>
<td style="text-align: right;">0.774317</td>
<td>Lower</td>
</tr>
<tr class="even">
<td>Change</td>
<td>Mean prediction-to-source similarity</td>
<td style="text-align: right;">0.903898</td>
<td style="text-align: right;">0.175191</td>
<td style="text-align: right;">1.000000</td>
<td>Descriptive</td>
</tr>
<tr class="odd">
<td>Change</td>
<td>Mean observed follow-up-to-source similarity</td>
<td style="text-align: right;">0.225683</td>
<td style="text-align: right;">0.225683</td>
<td style="text-align: right;">0.225683</td>
<td>Descriptive</td>
</tr>
</tbody>
</table>
<p>The projection improves three of six agreement measures, worsens two, and ties on exact match. Its clearest gains concern form and amount of change: word-count MAE falls by 15.04 words, and source-similarity MAE falls by 0.096102. But the mean predicted source similarity remains 0.678215 above the observed mean. Extracting supposedly enduring signifiers does not come close to reproducing how radically people rewrite their self-descriptions.</p>
<p>Trajectory retrieval creates the opposite pattern. Its mean source similarity (<code>0.175191</code>) is close to the observed <code>0.225683</code>, so source-similarity MAE falls to <code>0.136074</code>. But every non-exact agreement metric is lower than both continuity baselines. Generating a plausibly different response is therefore not equivalent to predicting the content of the focal person’s future self-description.</p>
</section>
<section id="paired-pattern" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="paired-pattern"><span class="header-section-number">6.2</span> Paired development-case pattern</h2>
<p>Positive effects favor stable-signifier projection. For agreement measures, the effect is projection minus repeat-2024; for errors, it is repeat-2024 error minus projection error. Exact match is omitted because all 50 cases tie at zero. A win, tie, or loss is evaluated within a person before averaging.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Metric</th>
<th style="text-align: right;" scope="col">Mean effect</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
<th style="text-align: right;" scope="col">Win / tie / loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normalized edit similarity</td>
<td style="text-align: right;">+0.006095</td>
<td style="text-align: right;">−0.001701 to +0.013890</td>
<td style="text-align: right;">24 / 14 / 12</td>
</tr>
<tr class="even">
<td>Token Jaccard similarity</td>
<td style="text-align: right;">+0.000838</td>
<td style="text-align: right;">−0.002383 to +0.004097</td>
<td style="text-align: right;">16 / 20 / 14</td>
</tr>
<tr class="odd">
<td>Token-overlap F1</td>
<td style="text-align: right;">−0.004759</td>
<td style="text-align: right;">−0.012300 to +0.002429</td>
<td style="text-align: right;">13 / 20 / 17</td>
</tr>
<tr class="even">
<td>ROUGE-L F1</td>
<td style="text-align: right;">+0.001869</td>
<td style="text-align: right;">−0.002268 to +0.005755</td>
<td style="text-align: right;">19 / 20 / 11</td>
</tr>
<tr class="odd">
<td>Character n-gram F1</td>
<td style="text-align: right;">−0.004241</td>
<td style="text-align: right;">−0.012240 to +0.003618</td>
<td style="text-align: right;">16 / 14 / 20</td>
</tr>
<tr class="even">
<td>Word-count error reduction</td>
<td style="text-align: right;">+15.040000</td>
<td style="text-align: right;">+1.180000 to +32.360000</td>
<td style="text-align: right;">20 / 20 / 10</td>
</tr>
<tr class="odd">
<td>Line-count error reduction</td>
<td style="text-align: right;">−2.960000</td>
<td style="text-align: right;">−5.540000 to −0.420000</td>
<td style="text-align: right;">15 / 12 / 23</td>
</tr>
<tr class="even">
<td>Source-similarity error reduction</td>
<td style="text-align: right;">+0.096102</td>
<td style="text-align: right;">+0.066064 to +0.129348</td>
<td style="text-align: right;">30 / 20 / 0</td>
</tr>
</tbody>
</table>
<p>The table changes the emphasis of the aggregate scorecard. None of the small agreement differences has an interval that excludes zero. In contrast, the projection’s lower word-count and source-similarity errors persist across the paired case resamples, while its line-count error is consistently worse. The source-similarity result is directional but inadequate in magnitude: even after improvement, the projection still remains much too close to the past.</p>
</section>
<section id="stable-projection-cv" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="stable-projection-cv"><span class="header-section-number">6.3</span> Training cross-validation repeats the mixed pattern</h2>
<p>The locked leave-one-out analysis refits the frozen projection 150 times. As in the development analysis, positive paired effects favor the projection; for error measures they are repeat-2024 error minus projection error.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Metric</th>
<th style="text-align: right;" scope="col">Projection</th>
<th style="text-align: right;" scope="col">Repeat 2024</th>
<th style="text-align: right;" scope="col">Mean effect</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normalized exact match</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000 to 0.000000</td>
</tr>
<tr class="even">
<td>Normalized edit similarity</td>
<td style="text-align: right;">0.276809</td>
<td style="text-align: right;">0.272662</td>
<td style="text-align: right;">+0.004147</td>
<td style="text-align: right;">+0.000652 to +0.007753</td>
</tr>
<tr class="odd">
<td>Token Jaccard similarity</td>
<td style="text-align: right;">0.133873</td>
<td style="text-align: right;">0.134297</td>
<td style="text-align: right;">−0.000424</td>
<td style="text-align: right;">−0.002229 to +0.001237</td>
</tr>
<tr class="even">
<td>Token-overlap F1</td>
<td style="text-align: right;">0.276737</td>
<td style="text-align: right;">0.280231</td>
<td style="text-align: right;">−0.003493</td>
<td style="text-align: right;">−0.007228 to −0.000077</td>
</tr>
<tr class="odd">
<td>ROUGE-L F1</td>
<td style="text-align: right;">0.200304</td>
<td style="text-align: right;">0.200017</td>
<td style="text-align: right;">+0.000287</td>
<td style="text-align: right;">−0.002003 to +0.002538</td>
</tr>
<tr class="even">
<td>Character n-gram F1</td>
<td style="text-align: right;">0.266194</td>
<td style="text-align: right;">0.267813</td>
<td style="text-align: right;">−0.001620</td>
<td style="text-align: right;">−0.005530 to +0.002270</td>
</tr>
<tr class="odd">
<td>Word-count MAE</td>
<td style="text-align: right;">46.986667</td>
<td style="text-align: right;">55.580000</td>
<td style="text-align: right;">+8.593333</td>
<td style="text-align: right;">+2.573333 to +15.266667</td>
</tr>
<tr class="even">
<td>Line-count MAE</td>
<td style="text-align: right;">9.066667</td>
<td style="text-align: right;">6.160000</td>
<td style="text-align: right;">−2.906667</td>
<td style="text-align: right;">−4.346833 to −1.480000</td>
</tr>
<tr class="odd">
<td>Source-similarity MAE</td>
<td style="text-align: right;">0.729214</td>
<td style="text-align: right;">0.799983</td>
<td style="text-align: right;">+0.070769</td>
<td style="text-align: right;">+0.054503 to +0.088484</td>
</tr>
</tbody>
</table>
<p>Only two nonzero agreement intervals exclude zero, and they point in opposite directions: normalized edit similarity improves slightly while token-overlap F1 worsens slightly. The other agreement differences remain unstable to cohort composition. The form/change findings are more reproducible: the method lowers word-count and source-similarity error but raises line-count error. Magnitude remains the substantive problem. Mean predicted source similarity is <code>0.929231</code>, versus <code>0.200017</code> for observed follow-ups, and 46.7% of predictions repeat the source exactly while no observed follow-up does.</p>
<p>The direction of all three error results matches development; four of five non-exact agreement directions also match, with token Jaccard shifting from a tiny positive difference to a tiny negative one. This is useful recurrence within the same method-development corpus, not independent replication.</p>
</section>
<section id="extractive-limits" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="extractive-limits"><span class="header-section-number">6.4</span> Lexical novelty and extractive ceilings</h2>
<p>The observed follow-ups contain substantial new lexical material. On an average case, 73.1727% of distinct follow-up token types are absent from the earlier response (95% case-bootstrap interval: 69.7982%–76.5607%). When token frequencies are respected, 65.0621% of follow-up token occurrences cannot be copied from the source without reusing tokens beyond their source counts (59.2663%–70.6149%). Conversely, only 24.9892% of distinct source token types recur at follow-up (22.0060%–28.0466%).</p>
<p>Even an oracle with access to the observed future is constrained. Its mean extractive ceilings are 0.268273 for unique-token Jaccard, 0.484206 for bag-of-words F1, and 0.374081 for source-order subsequence ROUGE-L F1. The actual projection reaches 0.142768, 0.307444, and 0.227552 on those measures. These comparisons reveal two failures at once: the current extractor does not reach the retrospective extractive ceiling, and no extractor can generate the many identity signifiers expressed only at follow-up.</p>
</section>
<section id="trajectory-retrieval" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="trajectory-retrieval"><span class="header-section-number">6.5</span> Retrieval predicts novelty volume, not novel content</h2>
<p>Positive paired effects favor trajectory retrieval. For errors, the effect is stable-projection error minus retrieval error. Retrieval loses agreement and word-count accuracy, modestly improves line-count error with an interval that spans zero, and dramatically improves source-similarity error.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Metric</th>
<th style="text-align: right;" scope="col">Retrieval</th>
<th style="text-align: right;" scope="col">Stable projection</th>
<th style="text-align: right;" scope="col">Paired effect</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normalized exact match</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000 to 0.000000</td>
</tr>
<tr class="even">
<td>Normalized edit similarity</td>
<td style="text-align: right;">0.253360</td>
<td style="text-align: right;">0.298061</td>
<td style="text-align: right;">−0.044701</td>
<td style="text-align: right;">−0.072824 to −0.018705</td>
</tr>
<tr class="odd">
<td>Token Jaccard similarity</td>
<td style="text-align: right;">0.080427</td>
<td style="text-align: right;">0.142768</td>
<td style="text-align: right;">−0.062342</td>
<td style="text-align: right;">−0.081759 to −0.043776</td>
</tr>
<tr class="even">
<td>Token-overlap F1</td>
<td style="text-align: right;">0.194693</td>
<td style="text-align: right;">0.307444</td>
<td style="text-align: right;">−0.112751</td>
<td style="text-align: right;">−0.170815 to −0.058175</td>
</tr>
<tr class="odd">
<td>ROUGE-L F1</td>
<td style="text-align: right;">0.150924</td>
<td style="text-align: right;">0.227552</td>
<td style="text-align: right;">−0.076628</td>
<td style="text-align: right;">−0.126464 to −0.030063</td>
</tr>
<tr class="even">
<td>Character n-gram F1</td>
<td style="text-align: right;">0.212660</td>
<td style="text-align: right;">0.292293</td>
<td style="text-align: right;">−0.079633</td>
<td style="text-align: right;">−0.112019 to −0.049794</td>
</tr>
<tr class="odd">
<td>Word-count MAE</td>
<td style="text-align: right;">59.640000</td>
<td style="text-align: right;">41.640000</td>
<td style="text-align: right;">−18.000000</td>
<td style="text-align: right;">−30.120500 to −6.160000</td>
</tr>
<tr class="even">
<td>Line-count MAE</td>
<td style="text-align: right;">8.340000</td>
<td style="text-align: right;">9.760000</td>
<td style="text-align: right;">+1.420000</td>
<td style="text-align: right;">−1.860000 to +4.640000</td>
</tr>
<tr class="odd">
<td>Source-similarity MAE</td>
<td style="text-align: right;">0.136074</td>
<td style="text-align: right;">0.678215</td>
<td style="text-align: right;">+0.542141</td>
<td style="text-align: right;">+0.463332 to +0.616781</td>
</tr>
</tbody>
</table>
<p>The locked novelty criterion tells the same story more precisely. Retrieval’s mean predicted unique-token novelty (<code>0.801727</code>) is much closer to the observed mean (<code>0.731727</code>) than either stable projection or repeat-2024 (<code>0</code> for both), so it passes the plan’s novelty-volume criterion. Its case-level novelty MAE is <code>0.139032</code>. Occurrence novelty is also close in aggregate (<code>0.727677</code> predicted versus <code>0.650621</code> observed).</p>
<p>However, novelty volume is not novel-content recovery. Among token types that retrieval introduces beyond the focal source, mean precision against the observed new token types is only <code>0.070466</code> (case-bootstrap interval <code>0.052133</code>–<code>0.090859</code>), recall is <code>0.085362</code> (<code>0.065937</code>–<code>0.106057</code>), and F1 is <code>0.067109</code> (<code>0.052917</code>–<code>0.082272</code>). Retrieval knows that a future response will look different, but mostly borrows the wrong person’s differences.</p>
</section>
<section id="novelty-prior" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="novelty-prior"><span class="header-section-number">6.6</span> Person matching does not beat common additions</h2>
<p>The volume-matched marginal prior predicts a mean 46.94 novel token types per case, exactly equal to retrieval by construction. Despite lacking any person-matching rule, it recovers more of the observed novel vocabulary:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Novel-type measure</th>
<th style="text-align: right;" scope="col">Marginal prior</th>
<th style="text-align: right;" scope="col">Trajectory retrieval</th>
<th style="text-align: right;" scope="col">Paired difference</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Precision</td>
<td style="text-align: right;">0.176545</td>
<td style="text-align: right;">0.070466</td>
<td style="text-align: right;">+0.106079</td>
<td style="text-align: right;">+0.068782 to +0.154891</td>
</tr>
<tr class="even">
<td>Recall</td>
<td style="text-align: right;">0.172611</td>
<td style="text-align: right;">0.085362</td>
<td style="text-align: right;">+0.087249</td>
<td style="text-align: right;">+0.062210 to +0.113649</td>
</tr>
<tr class="odd">
<td>F1</td>
<td style="text-align: right;">0.142637</td>
<td style="text-align: right;">0.067109</td>
<td style="text-align: right;">+0.075528</td>
<td style="text-align: right;">+0.055927 to +0.094990</td>
</tr>
</tbody>
</table>
<p>Positive differences favor the marginal prior. It wins 40 cases, ties 6, and loses 4 on each measure. The common additions include syntactic vocabulary such as <em>an</em>, <em>in</em>, <em>my</em>, <em>is</em>, and <em>who</em>, but also more content-bearing words such as <em>friend</em>, <em>lover</em>, <em>kind</em>, <em>creative</em>, and <em>life</em>. This means the earlier retrieval F1 cannot be read as evidence that matching text and demographics identified person-specific new signifiers. At matched volume, a coarse cohort-level base rate is substantially stronger.</p>
<p>The result does not establish that novel identity content is inherently unpredictable. It establishes a stricter baseline for future work: an individualized novelty model should beat common training additions at a comparable prediction volume before its gains are attributed to person-level conditioning.</p>
</section>
<section id="source-conditioned-additions" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="source-conditioned-additions"><span class="header-section-number">6.7</span> Source-token conditioning also loses to common additions</h2>
<p>The fixed source-conditioned ranking does not clear that baseline in its training-only leave-one-out test. Across all 150 held-out training cases, the mean recovered fraction is <code>0.145238</code>, compared with <code>0.160992</code> for the marginal-addition ranking:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Training leave-one-out result</th>
<th style="text-align: right;" scope="col">Source-conditioned</th>
<th style="text-align: right;" scope="col">Marginal additions</th>
<th style="text-align: right;" scope="col">Paired difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean novel-type recovered fraction</td>
<td style="text-align: right;">0.145238</td>
<td style="text-align: right;">0.160992</td>
<td style="text-align: right;">−0.015754</td>
</tr>
<tr class="even">
<td>Median novel-type recovered fraction</td>
<td style="text-align: right;">0.141177</td>
<td style="text-align: right;">0.156250</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>Case wins / ties / losses</td>
<td style="text-align: right;">19 / 63 / 68</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Paired case-bootstrap 95% interval</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−0.020829 to −0.010736</td>
</tr>
</tbody>
</table>
<p>The interval excludes zero in the direction favoring the marginal ranking. Thus, under the locked interpretation rule, the source-conditioned method provides no incremental advantage. One plausible explanation is that choosing the strongest source-token cue promotes sparse, idiosyncratic pairs that fail to recur in the held-out person, while the marginal ranking spends more of its fixed budget on common additions; the analysis does not isolate that mechanism.</p>
<p>This is a bounded negative result, not evidence that source signifiers contain no predictive information. The rule tests only token pairs, not phrases, semantics, interactions, or predicted deletions. Its mean candidate-vocabulary ceiling is <code>0.773139</code>: about 22.7% of held-out additions are absent from every other training follow-up’s additions and cannot be selected by either ranking. Most importantly, the oracle budget comes from the held-out future. The result compares ranking quality within this training cohort; it is not development or private-test performance.</p>
</section>
<section id="neighborhood-additions" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="neighborhood-additions"><span class="header-section-number">6.8</span> Regularized neighborhoods still lose to common additions</h2>
<p>Pooling rather than maximizing person-conditioned evidence narrows the deficit but does not clear the marginal baseline:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Training leave-one-out result</th>
<th style="text-align: right;" scope="col">Regularized neighborhood</th>
<th style="text-align: right;" scope="col">Marginal additions</th>
<th style="text-align: right;" scope="col">Paired difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean novel-type recovered fraction</td>
<td style="text-align: right;">0.149007</td>
<td style="text-align: right;">0.160992</td>
<td style="text-align: right;">−0.011984</td>
</tr>
<tr class="even">
<td>Median novel-type recovered fraction</td>
<td style="text-align: right;">0.148542</td>
<td style="text-align: right;">0.156250</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>Case wins / ties / losses</td>
<td style="text-align: right;">25 / 60 / 65</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Paired case-bootstrap 95% interval</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−0.018426 to −0.005693</td>
</tr>
</tbody>
</table>
<p>The interval again excludes zero in the direction favoring common additions. The neighborhood and marginal top sets overlap by <code>0.739706</code> on average, so the personalized method changes about 26.0% of guesses rather than merely reproducing its comparator. Mean cosine similarity across the 30 selected neighbors is only <code>0.169564</code>, consistent with a diffuse local neighborhood, although this diagnostic cannot determine why its substitutions are worse.</p>
<p>The result strengthens the bounded inference across two specifications. A maximum source-token association loses by 1.58 percentage points; a pooled, strongly regularized text-and-demographic neighborhood loses by 1.20 points. It does not follow that individualized prediction is impossible. Both methods operate on surface lexical overlap, both use an oracle future-token budget, and both draw candidates from other cases’ additions. The shared candidate-vocabulary ceiling remains <code>0.773139</code>.</p>
</section>
<section id="change-volume" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="change-volume"><span class="header-section-number">6.9</span> Neighborhoods predict some revision volume</h2>
<p>When the oracle addition budget is removed, the same neighborhood has a more limited but positive role. It improves absolute-error forecasts for how many distinct token types are added and deleted and for follow-up word count:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Training leave-one-out outcome</th>
<th style="text-align: right;" scope="col">Neighborhood MAE</th>
<th style="text-align: right;" scope="col">Source-calibrated marginal MAE</th>
<th style="text-align: right;" scope="col">Error reduction</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Add count</td>
<td style="text-align: right;">20.126667</td>
<td style="text-align: right;">21.340000</td>
<td style="text-align: right;">+1.213333</td>
<td style="text-align: right;">+0.680000 to +1.740000</td>
</tr>
<tr class="even">
<td>Delete count</td>
<td style="text-align: right;">5.336275</td>
<td style="text-align: right;">5.614935</td>
<td style="text-align: right;">+0.278660</td>
<td style="text-align: right;">+0.022274 to +0.545876</td>
</tr>
<tr class="odd">
<td>Follow-up word count</td>
<td style="text-align: right;">52.940000</td>
<td style="text-align: right;">56.080000</td>
<td style="text-align: right;">+3.140000</td>
<td style="text-align: right;">+1.093333 to +5.213333</td>
</tr>
<tr class="even">
<td>Follow-up line count</td>
<td style="text-align: right;">6.160000</td>
<td style="text-align: right;">6.160000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000 to 0.000000</td>
</tr>
<tr class="odd">
<td>Source similarity</td>
<td style="text-align: right;">0.106781</td>
<td style="text-align: right;">0.109648</td>
<td style="text-align: right;">+0.002867</td>
<td style="text-align: right;">−0.000960 to +0.006730</td>
</tr>
</tbody>
</table>
<p>Positive reductions favor the regularized neighborhood. Its Add-count forecast wins 79 cases, ties 17, and loses 54; Delete count wins 88, ties 5, and loses 57; word count wins 82, ties 13, and loses 55. The line-count forecasts are identical for all cases because both weighted medians select the same modeled line change. The source-similarity point estimate favors neighborhoods, but its interval spans zero.</p>
<p>The magnitudes are modest: Add-count MAE falls by 5.7%, Delete-count MAE by 5.0%, and word-count MAE by 5.6% relative to their comparators. Still, the direction matters. Surface text and coarse demographics contain some case-specific information about <em>how much</em> personally expressed identity will be revised, even though the same representation makes worse choices about <em>which</em> new tokens will appear. These are volume and form forecasts within the selected training cohort, not full-text forecasts or evidence that demographic similarity is an ipseological mechanism.</p>
</section>
<section id="change-distributions" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="change-distributions"><span class="header-section-number">6.10</span> Neighborhood distributions improve only word-count forecasts</h2>
<p>Scoring complete predictive distributions narrows the point-forecast result. Only follow-up word count has a paired CRPS interval that excludes zero in the direction favoring the neighborhood:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Training leave-one-out outcome</th>
<th style="text-align: right;" scope="col">Neighborhood CRPS</th>
<th style="text-align: right;" scope="col">Source-calibrated marginal CRPS</th>
<th style="text-align: right;" scope="col">CRPS reduction</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Add count</td>
<td style="text-align: right;">14.438038</td>
<td style="text-align: right;">14.650556</td>
<td style="text-align: right;">+0.212518</td>
<td style="text-align: right;">−0.071030 to +0.497525</td>
</tr>
<tr class="even">
<td>Delete count</td>
<td style="text-align: right;">3.853656</td>
<td style="text-align: right;">3.926457</td>
<td style="text-align: right;">+0.072801</td>
<td style="text-align: right;">−0.036356 to +0.178244</td>
</tr>
<tr class="odd">
<td>Follow-up word count</td>
<td style="text-align: right;">38.156852</td>
<td style="text-align: right;">40.672695</td>
<td style="text-align: right;">+2.515843</td>
<td style="text-align: right;">+1.008212 to +4.059792</td>
</tr>
<tr class="even">
<td>Follow-up line count</td>
<td style="text-align: right;">4.922609</td>
<td style="text-align: right;">4.910848</td>
<td style="text-align: right;">−0.011761</td>
<td style="text-align: right;">−0.097952 to +0.081212</td>
</tr>
<tr class="odd">
<td>Source similarity</td>
<td style="text-align: right;">0.074684</td>
<td style="text-align: right;">0.077171</td>
<td style="text-align: right;">+0.002486</td>
<td style="text-align: right;">−0.000106 to +0.005180</td>
</tr>
</tbody>
</table>
<p>The word-count neighborhood wins 83 cases and loses 67 on CRPS. Its central 80% interval covers 84.7% of cases, compared with 80.7% for the marginal distribution, while mean width rises from <code>149.960000</code> to <code>154.526667</code> words. Despite that modest widening, mean interval score improves from <code>264.626667</code> to <code>244.926667</code>: the paired reduction is <code>+19.700000</code> with interval <code>+3.873167</code> to <code>+37.193333</code>. Source-similarity interval score also improves, but its primary CRPS interval spans zero. The other interval-score comparisons span zero as well.</p>
<p>These distributional scores do not overturn the point-forecast findings. Rather, they locate their strongest probabilistic support in follow-up length. The Add and Delete medians improve absolute error, but their empirical distributions do not establish stable CRPS gains. Line-count intervals are substantially over-covering (96.7% marginal and 92.7% neighborhood against 80% nominal), showing that apparent uncertainty can be broad without being informative. None of these quantities identifies the future signifiers.</p>
</section>
<section id="feature-ablation" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="feature-ablation"><span class="header-section-number">6.11</span> Earlier self-description carries most word-count signal</h2>
<p>The required replication passed for all 150 cases and five outcomes. For the primary follow-up word-count outcome, text-only matching preserves most of the combined neighborhood’s advantage, while demographics-only matching does not establish an improvement over the marginal distribution:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th scope="col">Word-count predictive distribution</th>
<th style="text-align: right;" scope="col">Mean CRPS</th>
<th scope="col">Locked paired contrast</th>
<th style="text-align: right;" scope="col">CRPS reduction</th>
<th style="text-align: right;" scope="col">Paired case-bootstrap 95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Source-calibrated marginal</td>
<td style="text-align: right;">40.672695</td>
<td>—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Text only</td>
<td style="text-align: right;">38.374556</td>
<td>Marginal minus text only</td>
<td style="text-align: right;">+2.298139</td>
<td style="text-align: right;">+0.816444 to +3.865823</td>
</tr>
<tr class="odd">
<td>Demographics only</td>
<td style="text-align: right;">40.471984</td>
<td>Marginal minus demographics only</td>
<td style="text-align: right;">+0.200711</td>
<td style="text-align: right;">−0.479832 to +0.861529</td>
</tr>
<tr class="even">
<td>Combined</td>
<td style="text-align: right;">38.156852</td>
<td>Text only minus combined</td>
<td style="text-align: right;">+0.217704</td>
<td style="text-align: right;">+0.024229 to +0.420871</td>
</tr>
</tbody>
</table>
<p>Text-only matching wins 84 cases and loses 66 against the marginal. The combined model wins 85 and loses 65 against text-only. Thus the earlier self-description carries nearly all of the supported response-length signal; the ten coarse demographic fields alone do not beat the source-calibrated marginal. Their small incremental benefit conditional on text is compatible with weak complementary information, not a stand-alone demographic mechanism.</p>
<p>The secondary diagnostics do not support a general feature-family conclusion. For Add count, Delete count, and line count, every fixed ablation contrast has an interval spanning zero. Text-only matching improves source-similarity CRPS over the marginal by <code>+0.002964</code>, but its repeated-analysis interval barely excludes zero (<code>+0.000051</code> to <code>+0.006065</code>), and adding demographics to text does not improve that outcome. The primary result remains about response length, not future signifiers or revision volume generally.</p>
</section>
<section id="submission" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="submission"><span class="header-section-number">6.12</span> Frozen test submission</h2>
<p>The method generated one nonblank prediction for every test ID in the required order. The pinned official validator returned <code>VALID: 81 predictions</code>. The frozen CSV has SHA-256:</p>
<pre class="text"><code>a463d9e314069357f050c9f2270acfad59165db2c0bab19322d46517444d9ab3</code></pre>
<p>The organizer must run the private test evaluator. Until that happens, the private-test performance remains unknown; neither public-development results nor the training-only ranking diagnostic substitutes for it.</p>
</section>
</section>
<section id="discussion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Discussion</h1>
<p>The stable-signifier projection does learn something useful about response form and degree of change. Yet improved prediction of how much a response will change is not the same as predicting what new identity content will appear. The novelty diagnostic makes that distinction measurable: most future lexical material lies outside the earlier response, while the method is definitionally restricted to it. A next-generation model needs a mechanism for both deletion and creation, evaluated without sacrificing the interpretability of these paired diagnostics.</p>
<p>Leave-one-out cross-validation makes this conclusion less dependent on the 50 reused development cases. Its larger training-cohort analysis reproduces all three directional error results and the overall lack of a uniform agreement gain. The projection can adjust length and continuity without solving content: its small edit-similarity gain coexists with a small token-overlap loss and extreme overprediction of source continuity.</p>
<p>Matched-trajectory retrieval sharpens this inference. It supplies deletion and creation in approximately the observed proportions, but the transferred novel content is rarely person-correct. The problem is not merely calibrating how different the next self-description will be. A useful forecast must condition new signifiers on the individual without collapsing back into verbatim continuity.</p>
<p>The marginal control tightens that conclusion. Retrieval not only recovers little new vocabulary; it recovers less than a person-agnostic training prior given the same number of guesses. The diagnostic also disciplines the language of the report: token recovery is not automatically signifier recovery, because many high-base-rate additions are connective or generic words. Future person-specific models need to demonstrate value beyond both continuity and marginal lexical prevalence.</p>
<p>The two leave-one-out conditioned results make that requirement more specific. Merely finding the strongest smoothed source-token-to-Add association is not enough, and replacing that maximum with a strongly regularized 30-neighbor ensemble still sacrifices 1.20 percentage points relative to marginal prevalence. Surface lexical and coarse demographic similarity have now failed in both single-trajectory and pooled forms. Better individualization will need richer context, genuinely semantic synthesis, or new longitudinal evidence; it should establish an incremental training-only advantage before reopening the heavily reused development comparison.</p>
<p>The prospective volume analysis qualifies that negative content result. The fixed neighborhood improves three no-oracle quantity forecasts even while its oracle-budget lexical ranking loses to marginal additions. Person conditioning therefore is not uniformly uninformative: it helps estimate the extent of revision but has not identified its future signifiers. A synthesizing model should preserve that modest calibration signal while demonstrating content value beyond marginal prevalence. The probabilistic extension further qualifies the claim: the clearest distributional gain is for follow-up word count, while Add and Delete improvements are limited to point forecasts under the current evidence. The ablation now locates most of the supported word-count distribution signal in the earlier self-description itself. Demographics alone do not improve the marginal forecast; their much smaller incremental gain appears only in combination with text and does not establish that demographic resemblance is an ipseological mechanism.</p>
<section id="reproducibility" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="reproducibility"><span class="header-section-number">7.1</span> Reproducibility</h2>
<p>The complete open materials are:</p>
<ul>
<li><a href="ANALYSIS_PLAN_CHANGE_DISTRIBUTIONS.md"><code>ANALYSIS_PLAN_CHANGE_DISTRIBUTIONS.md</code></a> — pre-analysis lock for probabilistic revision-volume forecasts;</li>
<li><a href="ANALYSIS_PLAN_FEATURE_ABLATION.md"><code>ANALYSIS_PLAN_FEATURE_ABLATION.md</code></a> — pre-analysis lock for separating text and demographic source features;</li>
<li><a href="ANALYSIS_PLAN_CHANGE_VOLUME.md"><code>ANALYSIS_PLAN_CHANGE_VOLUME.md</code></a> — pre-analysis lock for prospective revision-volume forecasts;</li>
<li><a href="ANALYSIS_PLAN_NEIGHBORHOOD_ADDITIONS.md"><code>ANALYSIS_PLAN_NEIGHBORHOOD_ADDITIONS.md</code></a> — pre-analysis lock for the regularized-neighborhood comparison;</li>
<li><a href="ANALYSIS_PLAN_SOURCE_CONDITIONED_ADDITIONS.md"><code>ANALYSIS_PLAN_SOURCE_CONDITIONED_ADDITIONS.md</code></a> — pre-analysis lock for the training-only ranking comparison;</li>
<li><a href="ANALYSIS_PLAN_STABLE_PROJECTION_CROSS_VALIDATION.md"><code>ANALYSIS_PLAN_STABLE_PROJECTION_CROSS_VALIDATION.md</code></a> — pre-analysis lock for leave-one-out validation of the frozen projection;</li>
<li><a href="ANALYSIS_PLAN_TRAJECTORY_RETRIEVAL.md"><code>ANALYSIS_PLAN_TRAJECTORY_RETRIEVAL.md</code></a> — pre-prediction method and evaluation lock;</li>
<li><a href="analysis/analyze_dev_diagnostics.py"><code>analysis/analyze_dev_diagnostics.py</code></a> — hash-guarded paired bootstrap and extractive-limit analysis;</li>
<li><a href="analysis/analyze_change_distributions.py"><code>analysis/analyze_change_distributions.py</code></a> — hash-guarded leave-one-out predictive-distribution evaluation;</li>
<li><a href="analysis/analyze_change_volume.py"><code>analysis/analyze_change_volume.py</code></a> — hash-guarded leave-one-out response-form and revision-volume forecasts;</li>
<li><a href="analysis/analyze_feature_ablation.py"><code>analysis/analyze_feature_ablation.py</code></a> — hash-guarded leave-one-out source-feature ablation;</li>
<li><a href="analysis/analyze_novelty_prior.py"><code>analysis/analyze_novelty_prior.py</code></a> — volume-matched marginal-addition diagnostic;</li>
<li><a href="analysis/analyze_neighborhood_additions.py"><code>analysis/analyze_neighborhood_additions.py</code></a> — hash-guarded regularized-neighborhood leave-one-out comparison;</li>
<li><a href="analysis/analyze_source_conditioned_additions.py"><code>analysis/analyze_source_conditioned_additions.py</code></a> — hash-guarded leave-one-out source-conditioned comparison;</li>
<li><a href="analysis/analyze_stable_projection_cross_validation.py"><code>analysis/analyze_stable_projection_cross_validation.py</code></a> — hash-guarded leave-one-out stable-projection evaluation;</li>
<li><a href="analysis/analyze_trajectory_retrieval.py"><code>analysis/analyze_trajectory_retrieval.py</code></a> — complete paired and novelty comparison under the lock;</li>
<li><a href="analysis/stable_signifier_projection.py"><code>analysis/stable_signifier_projection.py</code></a> — standard-library generator;</li>
<li><a href="analysis/trajectory_retrieval.py"><code>analysis/trajectory_retrieval.py</code></a> — standard-library matched-trajectory generator;</li>
<li><a href="results/stable_signifier_dev_diagnostics.json"><code>results/stable_signifier_dev_diagnostics.json</code></a> — complete machine-readable post hoc diagnostic results;</li>
<li><a href="results/change_distributions_train_analysis.json"><code>results/change_distributions_train_analysis.json</code></a> — complete machine-readable probabilistic-forecast result;</li>
<li><a href="results/change_distributions_train_audit.csv"><code>results/change_distributions_train_audit.csv</code></a> — all 150 cases’ CRPS and central-interval diagnostics;</li>
<li><a href="results/change_volume_train_analysis.json"><code>results/change_volume_train_analysis.json</code></a> — complete machine-readable change-volume result;</li>
<li><a href="results/change_volume_train_audit.csv"><code>results/change_volume_train_audit.csv</code></a> — all 150 cases’ observed quantities, predictions, errors, and paired effects;</li>
<li><a href="results/feature_ablation_train_analysis.json"><code>results/feature_ablation_train_analysis.json</code></a> — complete machine-readable feature-ablation result;</li>
<li><a href="results/feature_ablation_train_audit.csv"><code>results/feature_ablation_train_audit.csv</code></a> — all 150 cases’ marginal and ablated CRPS values;</li>
<li><a href="results/novelty_prior_dev_analysis.json"><code>results/novelty_prior_dev_analysis.json</code></a> — complete marginal-prior comparison and paired uncertainty;</li>
<li><a href="results/novelty_prior_token_audit.csv"><code>results/novelty_prior_token_audit.csv</code></a> — token ranks, frequencies, prediction counts, and correct-recovery counts;</li>
<li><a href="results/neighborhood_additions_train_analysis.json"><code>results/neighborhood_additions_train_analysis.json</code></a> — complete regularized-neighborhood result;</li>
<li><a href="results/neighborhood_additions_train_audit.csv"><code>results/neighborhood_additions_train_audit.csv</code></a> — neighbors, budgets, reachability, hits, overlap, and paired case effects;</li>
<li><a href="results/source_conditioned_additions_train_analysis.json"><code>results/source_conditioned_additions_train_analysis.json</code></a> — complete machine-readable leave-one-out result;</li>
<li><a href="results/source_conditioned_additions_train_audit.csv"><code>results/source_conditioned_additions_train_audit.csv</code></a> — budgets, reachable additions, hits, scores, and paired case effects;</li>
<li><a href="results/stable_signifier_dev_predictions.csv"><code>results/stable_signifier_dev_predictions.csv</code></a> — all 50 public development predictions;</li>
<li><a href="results/stable_signifier_dev_scorecard.json"><code>results/stable_signifier_dev_scorecard.json</code></a> — complete machine-readable scorecard;</li>
<li><a href="results/stable_projection_train_cv_analysis.json"><code>results/stable_projection_train_cv_analysis.json</code></a> — complete paired training cross-validation result;</li>
<li><a href="results/stable_projection_train_cv_predictions.csv"><code>results/stable_projection_train_cv_predictions.csv</code></a> — all 150 leave-one-out fold predictions;</li>
<li><a href="results/trajectory_retrieval_dev_analysis.json"><code>results/trajectory_retrieval_dev_analysis.json</code></a> — complete locked paired comparison and novelty diagnostics;</li>
<li><a href="results/trajectory_retrieval_dev_audit.csv"><code>results/trajectory_retrieval_dev_audit.csv</code></a> — development-to-training match IDs and cosine similarities;</li>
<li><a href="results/trajectory_retrieval_dev_predictions.csv"><code>results/trajectory_retrieval_dev_predictions.csv</code></a> — all 50 retrieved development forecasts;</li>
<li><a href="results/trajectory_retrieval_dev_scorecard.json"><code>results/trajectory_retrieval_dev_scorecard.json</code></a> — complete official retrieval scorecard;</li>
<li><a href="submissions/aleph_initial_alpha_submission.csv"><code>submissions/aleph_initial_alpha_submission.csv</code></a> — frozen 81-case test artifact;</li>
<li><a href="submissions/aleph_initial_alpha_method.md"><code>submissions/aleph_initial_alpha_method.md</code></a> — submission-ready method card.</li>
</ul>
<p>Both generators use only the Python standard library. The challenge’s 17 public tests passed before the stable artifact was generated. Regenerating the stable development and test artifacts reproduced their hashes exactly; the retrieval pipeline separately hash-guards its inputs and fixed analysis plan.</p>
</section>
<section id="sources" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sources"><span class="header-section-number">7.2</span> Sources</h2>
<ul>
<li>Gneiting, T., &amp; Raftery, A. E. (2007). Strictly proper scoring rules, prediction, and estimation. <em>Journal of the American Statistical Association, 102</em>(477), 359–378. <a href="https://doi.org/10.1198/016214506000001437">https://doi.org/10.1198/016214506000001437</a></li>
<li>Jones, J. J. (2023). <a href="https://jasonjones.ninja/ipseology-a-new-science-of-the-self-book/"><em>Ipseology—A new science of the self</em></a>.</li>
<li>Jones, J. J. (2024). <a href="https://doi.org/10.31235/osf.io/eh9sk"><em>Predicting the self with generative AI</em></a> [Preprint]. SocArXiv. https://doi.org/10.31235/osf.io/eh9sk</li>
<li>Jones, J. J. (2026). <a href="https://arxiv.org/html/2607.02488"><em>Building the ipseome: Large, free, open, human identity data</em></a> [Preprint]. arXiv.</li>
<li>Jones, J. J. (2026). <a href="https://github.com/jasonjeffreyjones/predict-future-selves"><em>You can predict future selves with AI (or without AI)</em></a> [Data set and benchmark]. GitHub.</li>
</ul>
</section>
<section id="limitations" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="limitations"><span class="header-section-number">7.3</span> Limitations and next step</h2>
<p>An extractive method cannot predict genuinely new identities, experiences, or reframing. Token recurrence is not equivalent to identity-signifier endurance, and common wording can make a signifier look stable. The line splitter also turns some prose sentences into separate output lines, worsening line-count error. Finally, public-development-guided selection can overfit a 50-case set.</p>
<p>The stable-projection cross-validation withholds each case’s future from its own model fit, but it is not untouched confirmation. The training corpus had already informed the method, and cross-validation folds overlap heavily. Its case-bootstrap intervals describe this selected training cohort rather than a population. The published fold predictions are a derived benchmark-data adaptation under CC BY-NC-SA 4.0.</p>
<p>Trajectory retrieval adds different limitations. It transfers another participant’s public response rather than generating a person-specific future, and demographic similarity does not establish that identity change follows demographic categories. Its within-iteration lock reduces new analytic flexibility but cannot make previously inspected development data unseen.</p>
<p>The marginal-addition control is post hoc and deliberately narrow. It uses retrieval’s case-level novel-token count, so it is not an independent full-text forecast; it isolates content choice after holding opportunity volume equal. Its ranking is estimated from only 150 training pairs, and its lexical units include function words that are not necessarily identity signifiers. The derived token audit adapts the benchmark data and remains governed by the benchmark’s CC BY-NC-SA 4.0 license.</p>
<p>The source-conditioned comparison is locked and uses leave-one-out estimation, but it remains a training-cohort diagnostic with an oracle future-token budget. Its maximum-over-source-tokens rule can privilege sparse associations, the ten-case smoothing strength was adopted rather than tuned, and its tokens need not be semantic signifiers. The case audit is also a derived benchmark-data adaptation under CC BY-NC-SA 4.0.</p>
<p>The regularized-neighborhood comparison shares the oracle-budget and lexical identity-signifier limitations. Its 30-neighbor size and equal 30-case marginal prior were fixed without tuning, while its text-and-demographic representation was selected in earlier Project work. Coarse demographic similarity is not an ipseological mechanism. Its case audit is likewise a derived benchmark-data adaptation under CC BY-NC-SA 4.0.</p>
<p>The change-volume comparison removes that oracle budget, but its surface-text and coarse-demographic representation and its 30-neighbor, equal-shrinkage choices came from prior Project work rather than untouched selection. Its overlapping folds and case-bootstrap intervals characterize this selected training cohort, not a population. Count forecasts remain continuous to avoid an arbitrary rounding rule, Add/Delete tokens need not all be identity signifiers, and the derived case audit is governed by CC BY-NC-SA 4.0.</p>
<p>The probabilistic extension inherits all of those design constraints. Its weighted empirical distributions reuse the same outcomes, folds, representation, and fixed weights; they are not independently selected models. Central 80% intervals are discrete empirical quantiles, and coverage in 150 overlapping leave-one-out folds is descriptive rather than a population guarantee. Its derived case audit is also governed by CC BY-NC-SA 4.0.</p>
<p>The source-feature ablation is a dependent extension chosen after the combined word-count gain was known. It preserves the existing exact-value demographic features, so sparse categories and missing values can weaken demographics-only similarity. Its unadjusted secondary contrasts are repeated-analysis diagnostics, not an independent family of confirmatory tests. The derived case audit remains governed by CC BY-NC-SA 4.0.</p>
<p>The paired bootstrap treats development cases as the resampling unit, but the benchmark is a selected longitudinal cohort rather than a probability sample. Its intervals describe sensitivity to the composition of these 50 cases, not uncertainty for people in general. The lexical oracles use observed follow-ups and are deliberately unattainable; they must not be read as test predictions or achievable prospective scores.</p>
<p>The immediate next step is to submit the two prepared artifacts to the challenge organizer and add the complete private test scorecard, unchanged, to this report. Further fixed lexical re-rankers on the same 150 cases are unlikely to be informative without a substantively new representation. A later method should synthesize rather than copy novel content, show an incremental advantage over leave-one-out marginal additions before any additional development comparison, lock that comparison, and avoid private test feedback for tuning.</p>


</section>
</section>

</main> <!-- /main -->
<footer class="report-footer">
  <p>Virtual CSSERG — discover and document truth efficiently and at scale.</p>
  <div class="footer-links">
    <nav class="footer-group" data-footer-group="about" aria-label="About"><strong>About</strong> <a href="https://jasonjones.ninja/">Dr. Jason Jeffrey Jones</a> <a href="https://jasonjones.ninja/csserg/">CSSERG</a></nav>
    <nav class="footer-group" data-footer-group="open-work" aria-label="Open work"><strong>Open work</strong> <a href="https://github.com/jasonjeffreyjones/virtual-csserg/">GitHub repository</a> <a href="https://creativecommons.org/licenses/by/4.0/" rel="license"><img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png" alt="Creative Commons Attribution 4.0 International" width="88" height="31"></a></nav>
  </div>
</footer>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation" aria-label="Previous and next chapters">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Forecasting expressed identity">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Forecasting expressed identity</span>
      </a>
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>